version: '3.7'

services:

  # Payment Gateway
  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_gateway_db
      SPRING_DATASOURCE_USERNAME: db_username
      SPRING_DATASOURCE_PASSWORD: db_password
    depends_on:
      - mysql
    networks:
      - payment-gateway-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: payment-gateway-mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_DATABASE: payment_gateway_db
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - payment-gateway-network

  # WireMock for Simulating Acquiring Bank
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - payment-gateway-network

networks:
  payment-gateway-network:

volumes:
  mysql-data:
